# Generated by Django 5.1.4 on 2024-12-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD')], default='Computer Science', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='applied',
            field=models.ManyToManyField(to='users.applicant'),
        ),
        migrations.AlterField(
            model_name='education',
            name='faculty',
            field=models.CharField(max_length=50),
        ),
    ]
